### PR TITLE
fixed format_value to display properly

### PR DESCRIPTION
**Pull request by dedayoa**
Display proper Amount value in html input field

### CODE REVIEW

**Comment by patrys** [comment]
Huh, it seems that there's `PriceField` that handles `Price`s where it should be replaced by an `AmountField` that handles `Amount`s. There's no good way to handle a `Price` object with a single input.

**Comment by dedayoa** [comment]
@patrys but that's not the case - at least not obviously.
I am aware of the changes to both prices and django-prices (between 0.X.X and the 1.0) and have updated my code appropriately...but still have the issues I'm trying to remedy crop up.

**Comment by patrys** [comment]
I know, I'm commenting on the current state of `django-prices`, not your change. I think we need to rework the fields and widgets exposed to the UI.

**Comment by rafalp** [comment]
Hey @dedayoa! Thank you for reporting the issue and taking time to come up with the fix!

We've just released 1.0.0 beta 3 that includes fix as part of its changes.

**Pull request closed without merging**
